# Generated by Django 5.1.6 on 2025-03-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student',
            new_name='user',
        ),
    ]
